### ISSUE TITLE
Java Barchart example does not work

### ISSUE THREAD

**Issue by RollelBlade** [mdewilde/chart#28]
I used exactly the same java code as given on github. I had the following relevant code snipet in html:
<div style="width:75%;">
    <canvas id="canvasId"></canvas>
  </div>

  <script type="text/javascript">
  $(document).ready(function() {
	    $.ajax({
	        url: "http://127.0.0.1:8080/getdata"
	    }).then(function(graph) {
	    	var ctx = document.getElementById('canvasId');
	    	new Chart(ctx, graph);
	    });
	});
  </script>

**After executing the webapp I got the following error message**:
jQuery.Deferred exception: Cannot create property 'data' on string '{
  "data" : {
    "labels" : [ "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" ],
    "datasets" : [ {
      "data" : [ 65, 59, 80, 81, 56, 55, 40 ],
      "backgroundColor" : [ "rgba(255,0,0,1.000)", "rgba(0,128,0,1.000)", "rgba(0,0,255,1.000)", "rgba(255,255,0,1.000)", "rgba(255,165,0,1.000)", "rgba(128,128,128,1.000)", "rgba(0,0,0,1.000)" ],
      "borderWidth" : 2,
      "label" : "sample chart"
    } ]
  },
  "type" : "bar"
}' TypeError: Cannot create property 'data' on string '{
  "data" : {
    "labels" : [ "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" ],
    "datasets" : [ {
      "data" : [ 65, 59, 80, 81, 56, 55, 40 ],
      "backgroundColor" : [ "rgba(255,0,0,1.000)", "rgba(0,128,0,1.000)", "rgba(0,0,255,1.000)", "rgba(255,255,0,1.000)", "rgba(255,165,0,1.000)", "rgba(128,128,128,1.000)", "rgba(0,0,0,1.000)" ],
      "borderWidth" : 2,
      "label" : "sample chart"
    } ]
  },
  "type" : "bar"
}'
    at https://cdn.jsdelivr.net/npm/chart.js@2.8.0:7:92078
    at ni.construct (https://cdn.jsdelivr.net/npm/chart.js@2.8.0:7:92196)
    at new ni (https://cdn.jsdelivr.net/npm/chart.js@2.8.0:7:91964)
    at Object.<anonymous> (http://127.0.0.1:8080/:29:7)
    at e (https://code.jquery.com/jquery-3.4.1.min.js:2:29453)
    at t (https://code.jquery.com/jquery-3.4.1.min.js:2:29755) undefined

Any help is highly appreciated

**Comment by RollelBlade** [comment]
It was my mistake. I forgot to invoke the jQuery.parseJSON() function.
